import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { CustomersService } from '../customers.service';
import { ICustomers } from '../icustomers';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

@Component({
  selector: 'app-customers-new',
  templateUrl: './customers-new.component.html',
  styleUrls: ['./customers-new.component.scss'],
})
export class CustomersNewComponent extends BaseNewComponent<ICustomers> implements OnInit {
  title: string = 'New Customers';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public dialogRef: MatDialogRef<CustomersNewComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    public pickerDialogService: PickerDialogService,
    public customersService: CustomersService,
    public errorService: ErrorService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, customersService, errorService);
  }

  ngOnInit() {
    this.entityName = 'Customers';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.checkPassedData();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      address: [''],
      createdAt: [''],
      createdAtTime: ['12:00 AM'],
      email: ['', Validators.required],
      firstName: ['', Validators.required],
      lastName: ['', Validators.required],
      phone: [''],
      updatedAt: [''],
      updatedAtTime: ['12:00 AM'],
    });

    this.fields = [
      {
        name: 'address',
        label: 'address',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'createdAt',
        label: 'created At',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.Date,
      },
      {
        name: 'createdAtTime',
        label: 'created At Time',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.Time,
      },
      {
        name: 'email',
        label: 'email',
        isRequired: true,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'firstName',
        label: 'first Name',
        isRequired: true,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'lastName',
        label: 'last Name',
        isRequired: true,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'phone',
        label: 'phone',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'updatedAt',
        label: 'updated At',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.Date,
      },
      {
        name: 'updatedAtTime',
        label: 'updated At Time',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.Time,
      },
    ];
  }

  setAssociations() {
    this.associations = [];
    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let customers = this.itemForm.getRawValue();

    customers.createdAt = this.dataService.combineDateAndTime(customers.createdAt, customers.createdAtTime);
    delete customers.createdAtTime;
    customers.updatedAt = this.dataService.combineDateAndTime(customers.updatedAt, customers.updatedAtTime);
    delete customers.updatedAtTime;

    super.onSubmit(customers);
  }
}
