import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { SuppliersService } from '../suppliers.service';
import { ISuppliers } from '../isuppliers';
import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

@Component({
  selector: 'app-suppliers-details',
  templateUrl: './suppliers-details.component.html',
  styleUrls: ['./suppliers-details.component.scss'],
})
export class SuppliersDetailsComponent extends BaseDetailsComponent<ISuppliers> implements OnInit {
  title = 'Suppliers';
  parentUrl = 'suppliers';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public suppliersService: SuppliersService,
    public pickerDialogService: PickerDialogService,
    public errorService: ErrorService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(formBuilder, router, route, dialog, pickerDialogService, suppliersService, errorService);
  }

  ngOnInit() {
    this.entityName = 'Suppliers';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.getItem();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      address: [''],
      contactEmail: [''],
      contactName: [''],
      contactPhone: [''],
      createdAt: [''],
      createdAtTime: [''],
      name: ['', Validators.required],
      supplierId: [{ value: '', disabled: true }, Validators.required],
      updatedAt: [''],
      updatedAtTime: [''],
    });

    this.fields = [
      {
        name: 'address',
        label: 'address',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'contactEmail',
        label: 'contact Email',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'contactName',
        label: 'contact Name',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'contactPhone',
        label: 'contact Phone',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'createdAt',
        label: 'created At',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.Date,
      },
      {
        name: 'createdAtTime',
        label: 'created At Time',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.Time,
      },
      {
        name: 'name',
        label: 'name',
        isRequired: true,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'updatedAt',
        label: 'updated At',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.Date,
      },
      {
        name: 'updatedAtTime',
        label: 'updated At Time',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.Time,
      },
    ];
  }

  onItemFetched(item: ISuppliers) {
    this.item = item;
    this.itemForm.get('createdAt')?.setValue(item.createdAt ? new Date(item.createdAt) : null);
    this.itemForm.get('createdAtTime')?.setValue(this.suppliersService.formatDateStringToAMPM(item.createdAt));
    this.itemForm.get('updatedAt')?.setValue(item.updatedAt ? new Date(item.updatedAt) : null);
    this.itemForm.get('updatedAtTime')?.setValue(this.suppliersService.formatDateStringToAMPM(item.updatedAt));
    this.itemForm.patchValue(item);
  }

  setAssociations() {
    this.associations = [
      {
        column: [
          {
            key: 'supplierId',
            value: undefined,
            referencedkey: 'supplierId',
          },
        ],
        isParent: true,
        table: 'inventory',
        type: 'OneToMany',
        label: 'inventorys',
      },
    ];

    this.childAssociations = this.associations.filter((association) => {
      return association.isParent;
    });

    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let suppliers = this.itemForm.getRawValue();

    suppliers.createdAt = this.dataService.combineDateAndTime(suppliers.createdAt, suppliers.createdAtTime);
    delete suppliers.createdAtTime;
    suppliers.updatedAt = this.dataService.combineDateAndTime(suppliers.updatedAt, suppliers.updatedAtTime);
    delete suppliers.updatedAtTime;

    super.onSubmit(suppliers);
  }
}
